"""followers

Revision ID: 47831413639e
Revises: 8a213290f696
Create Date: 2018-11-07 11:07:09.239455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47831413639e'
down_revision = '8a213290f696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
